
name: Deploy to BYOD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy website
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ftpupload.net
          username: ${{ secrets.INFINITY_FTP_USER }}
          password: ${{ secrets.INFINITY_FTP_PASS }}
          server-dir: htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
